import "./globals.css";
import estedad from "@/public/assets/fonts/Estedad/fontEstedad";
import SubMenu from "@/components/SubMenu";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${estedad.className} font-sans`}>
      <body>
        {children}
        <SubMenu />
      </body>
    </html>
  );
}
